#!/bin/bash

r_flag=0

while getopts "r" opt; do
	case $opt in
		r)
			rm -rf ~/.config/nvim-test
			rm -rf ~/.local/share/nvim-test
			r_flag=1
	esac
done

if [[ "$r_flag" -eq 0 ]]; then
	mkdir -p ~/.config/nvim-test
	cp -r ./* ~/.config/nvim-test/
	NVIM_APPNAME=nvim-test nvim
fi
